routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('heykama.index');
    // return view('welcome');
});


Route::group(['as' => 'heykama.'], function (){

	Route::get('index',  [App\Http\Controllers\Frontend\HeykamaController::class, 'index'])->name('index');
	Route::get('profile',  [App\Http\Controllers\Frontend\HeykamaController::class, 'profile'])->name('profile');
	Route::get('about', [App\Http\Controllers\Frontend\HeykamaController::class, 'about'])->name('about');
	Route::get('contact', [App\Http\Controllers\Frontend\HeykamaController::class, 'contact'])->name('contact');
	Route::get('blog', [App\Http\Controllers\Frontend\HeykamaController::class, 'blog'])->name('blog');
	Route::get('detailjournal/{id}', [App\Http\Controllers\Frontend\HeykamaController::class, 'detailjournal'])->name('detailjournal');
	Route::get('shop', [App\Http\Controllers\Frontend\HeykamaController::class, 'shop'])->name('shop');
	Route::get('shopdetail/{id}', [App\Http\Controllers\Frontend\HeykamaController::class, 'shopdetail'])->name('shopdetail');
	Route::get('promo', [App\Http\Controllers\Frontend\HeykamaController::class, 'promo'])->name('promo');
	Route::get('features', [App\Http\Controllers\Frontend\HeykamaController::class, 'features'])->name('features');
	Route::get('cart', [App\Http\Controllers\Frontend\HeykamaController::class, 'cart'])->name('cart');
	Route::get('order', [App\Http\Controllers\Frontend\HeykamaController::class, 'order'])->name('order');
	Route::get('trfpage/{id}', [App\Http\Controllers\Frontend\HeykamaController::class, 'trfpage'])->name('trfpage');
	Route::post('addaddress', [App\Http\Controllers\Frontend\HeykamaController::class, 'addaddress'])->name('addaddress');



	Route::post('checkout', [App\Http\Controllers\Frontend\HeykamaController::class, 'checkout'])->name('checkout');
	Route::get('dashboard', [App\Http\Controllers\Backend\DashboardController::class, 'index'])->name('dashboard');
	Route::get('product', [App\Http\Controllers\Backend\ProductController::class, 'index'])->name('product');


	Route::get('category', [App\Http\Controllers\Backend\CategoryController::class, 'index'])->name('category');
	Route::post('addcategory', [App\Http\Controllers\Backend\CategoryController::class, 'create'])->name('addcategory');
	Route::post('editviewcategory', [App\Http\Controllers\Backend\CategoryController::class, 'create'])->name('editviewcategory');

	Route::get('uom', [App\Http\Controllers\Backend\UomController::class, 'index'])->name('uom');
	Route::post('adduom', [App\Http\Controllers\Backend\UomController::class, 'create'])->name('adduom');

	Route::get('producttype', [App\Http\Controllers\Backend\ProductTypeController::class, 'index'])->name('producttype');
	Route::post('addproducttype', [App\Http\Controllers\Backend\ProductTypeController::class, 'create'])->name('addproducttype');

	Route::get('supplier', [App\Http\Controllers\Backend\SupplierController::class, 'index'])->name('supplier');
	Route::post('addsupplier', [App\Http\Controllers\Backend\SupplierController::class, 'create'])->name('addsupplier');

	Route::get('customer', [App\Http\Controllers\Backend\CustomerController::class, 'index'])->name('customer');
	Route::post('addcustomer', [App\Http\Controllers\Backend\CustomerController::class, 'create'])->name('addcustomer');




	Route::post('addtocart', [App\Http\Controllers\Frontend\HeykamaController::class, 'addtocart'])->name('addtocart');
});




Auth::routes();


Route::group([
	'namespace' => 'Backend',
	'prefix' => 'backend',
	'as' => 'backend.',
], function () {


    Route::group(['as' => 'product.'], function (){
        Route::get('product', [App\Http\Controllers\Backend\ProductController::class, 'index'])->name('index');
        Route::get('product/addproduct', [App\Http\Controllers\Backend\ProductController::class, 'addproduct'])->name('addproduct');
        Route::get('product/addvarian/{id}', [App\Http\Controllers\Backend\ProductController::class, 'addvarian'])->name('addvarian');
        Route::get('product/addprice/{id}', [App\Http\Controllers\Backend\ProductController::class, 'addprice'])->name('addprice');
        Route::get('product/detailproduct/{id}', [App\Http\Controllers\Backend\ProductController::class, 'detailproduct'])->name('detailproduct');
        Route::get('product/editproduct/{id}', [App\Http\Controllers\Backend\ProductController::class, 'editproduct'])->name('editproduct');
        Route::get('product/editvariant/{id}', [App\Http\Controllers\Backend\ProductController::class, 'editvariant'])->name('editvariant');
        Route::get('product/modaleditvariant/{id}', [App\Http\Controllers\Backend\ProductController::class, 'modaleditvariant'])->name('modaleditvariant');

        Route::post('product/save', [App\Http\Controllers\Backend\ProductController::class, 'save'])->name('save');
        Route::post('product/edit', [App\Http\Controllers\Backend\ProductController::class, 'edit'])->name('edit');
        Route::post('product/delele', [App\Http\Controllers\Backend\ProductController::class, 'delele'])->name('delele');
        Route::post('product/delelevariant', [App\Http\Controllers\Backend\ProductController::class, 'delelevariant'])->name('delelevariant');
        Route::post('product/savevariant', [App\Http\Controllers\Backend\ProductController::class, 'savevariant'])->name('savevariant');
        Route::post('product/updatevariant', [App\Http\Controllers\Backend\ProductController::class, 'updatevariant'])->name('updatevariant');
        Route::post('product/variantupdate', [App\Http\Controllers\Backend\ProductController::class, 'variantupdate'])->name('variantupdate');
        Route::post('product/saveprice', [App\Http\Controllers\Backend\ProductController::class, 'saveprice'])->name('saveprice');
        Route::post('product/setproducttype', [App\Http\Controllers\Backend\ProductController::class, 'setproducttype'])->name('setproducttype');
    });

    Route::group(['as' => 'order.'], function (){
        Route::get('order', [App\Http\Controllers\Backend\OrderController::class, 'index'])->name('index');
        Route::get('order/detail/{id}', [App\Http\Controllers\Backend\OrderController::class, 'detail'])->name('detail');
    });

    Route::group(['as' => 'setting.'], function (){
        Route::get('setting', [App\Http\Controllers\Backend\SettingController::class, 'index'])->name('index');
        Route::post('setting/create', [App\Http\Controllers\Backend\SettingController::class, 'create'])->name('create');
        Route::get('setting/detail/{id}', [App\Http\Controllers\Backend\SettingController::class, 'detail'])->name('detail');
    });

    Route::group(['as' => 'promotion.'], function (){
        Route::get('promotion', [App\Http\Controllers\Backend\PromotionController::class, 'index'])->name('index');
        Route::get('promotion/listdatatable', [App\Http\Controllers\Backend\PromotionController::class, 'listdatatable'])->name('listdatatable');
    });

    Route::group(['as' => 'journal.'], function (){
        Route::get('journal', [App\Http\Controllers\Backend\JournalController::class, 'index'])->name('index');
        Route::post('journal/create', [App\Http\Controllers\Backend\JournalController::class, 'create'])->name('create');
        Route::get('journal/detail/{id}', [App\Http\Controllers\Backend\JournalController::class, 'detail'])->name('detail');
    });
    Route::group(['as' => 'about.'], function (){
        Route::get('about', [App\Http\Controllers\Backend\AboutController::class, 'index'])->name('index');
        Route::post('about/create', [App\Http\Controllers\Backend\AboutController::class, 'create'])->name('create');
        Route::get('about/detail/{id}', [App\Http\Controllers\Backend\AboutController::class, 'detail'])->name('detail');
    });
    Route::group(['as' => 'newslatter.'], function (){
        Route::get('newslatter', [App\Http\Controllers\Backend\NewlatterController::class, 'index'])->name('index');
        Route::post('newslatter/create', [App\Http\Controllers\Backend\NewlatterController::class, 'create'])->name('create');
        Route::get('newslatter/detail/{id}', [App\Http\Controllers\Backend\NewlatterController::class, 'detail'])->name('detail');
    });
    Route::group(['as' => 'user.'], function (){
        Route::get('user', [App\Http\Controllers\Backend\UserController::class, 'index'])->name('index');
        Route::get('user/add', [App\Http\Controllers\Backend\UserController::class, 'add'])->name('add');
        Route::get('user/edit/{id}', [App\Http\Controllers\Backend\UserController::class, 'edit'])->name('edit');
        Route::post('user/create', [App\Http\Controllers\Backend\UserController::class, 'create'])->name('create');
        Route::post('user/update', [App\Http\Controllers\Backend\UserController::class, 'update'])->name('update');
        Route::get('user/detail/{id}', [App\Http\Controllers\Backend\UserController::class, 'detail'])->name('detail');
    });

});

app/Http/Controllers/Backend/AboutController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Traits\FlashMessageTraits;
use DB;
class AboutController extends Controller
{
    use FlashMessageTraits;
    function __construct(

    )
    {
        //No session access from constructor work arround
        // $this->middleware(function ($request, $next)
        // {
        //     $this->user = session('data')->user;
        //     return $next($request);
        // });
    }

    public function index()
    {
        $data['breadcrumb'] = [
            'parent' => 'About',
            'child' => 'List About'
        ];
        $data['listcategory'] = $this->listcategory();
        return view('backend.about.index', $data);
    }

    public function detail($id)
    {
        $data['id'] = $id;
        $data['detail'] = $this->detaildata($id);
        return view('backend.about.detail', $data);
    }

    public function create(Request $request)
    {

        $sessionUser = $request->session()->get('session_user');
        $input = $request->all();
		$data = DB::table('journals')->insert(
			['created_by' => $sessionUser->id, 'title' => $input['title'], 'body' => $input['body'], 'status' => $input['status'], 'created_at' => date('Y-m-d H:i:s')]
		);
		if ( $data ) {
			$result = array( 'success' => true, 'message' => 'About Created Success!');
			return response()->json($result);
		} else {
			$result = array( 'success' => false, 'message' => 'About Created Failed!' );
			return response()->json($result);
		}
    }


	public function listcategory(){
		$hasil = DB::select('SELECT *
								FROM journals');
		return $hasil;
	}

	public function detaildata($id){
        $hasil = DB::table('journals')
        ->where('id',  $id)->first();
		return $hasil;
	}


}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Traits\FlashMessageTraits;
use DB;
class CategoryController extends Controller
{
    use FlashMessageTraits;
    function __construct(

    )
    {
        //No session access from constructor work arround
        // $this->middleware(function ($request, $next)
        // {
        //     $this->user = session('data')->user;
        //     return $next($request);
        // });
    }

    public function index()
    {
        $data['breadcrumb'] = [
            'parent' => 'Category',
            'child' => 'List Category'
        ];
        $data['listcategory'] = $this->listcategory();
        return view('backend.category.index', $data);
    }

    public function create(Request $request)
    {
        $input = $request->all();
		$data = DB::table('categories')->insert(
			['name' => $input['name'], 'description' => $input['description']]
		);
		if ( $data ) {
			$result = array( 'success' => true, 'message' => 'Category Created Success!');
			return response()->json($result);
		} else {
			$result = array( 'success' => false, 'message' => 'Category Created Failed!' );
			return response()->json($result);
		}
    }


	public function listcategory(){
		$hasil = DB::select('SELECT *
								FROM categories');
		return $hasil;
	}


}

app/Http/Controllers/Backend/CustomerController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Traits\FlashMessageTraits;
use DB;

class CustomerController extends Controller
{
    use FlashMessageTraits;
    function __construct(

    )
    {
        //No session access from constructor work arround
        // $this->middleware(function ($request, $next)
        // {
        //     $this->user = session('data')->user;
        //     return $next($request);
        // });
    }

    public function index()
    {
        $data['breadcrumb'] = [
            'parent' => 'Category',
            'child' => 'List Category'
        ];
        $data['listcategory'] = $this->listcategory();
        return view('backend.customer.index', $data);
    }

    public function create(Request $request)
    {
        $input = $request->all();
		$data = DB::table('customers')->insert(
			[
                'name' => $input['name'],
                'address' => $input['address'],
                'fax' => $input['fax'],
                'phone_number' => $input['phone_number'],
                'email' => $input['email']
            ]
		);
		if ( $data ) {
			$result = array( 'success' => true, 'message' => 'Category Created Success!');
			return response()->json($result);
		} else {
			$result = array( 'success' => false, 'message' => 'Category Created Failed!' );
			return response()->json($result);
		}
    }


	public function listcategory(){
		$hasil = DB::table('users')->where('type_user', 'CUSTOMER')->get();
		return $hasil;
	}


}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Traits\FlashMessageTraits;
use DB;
class DashboardController extends Controller
{
    use FlashMessageTraits;
    function __construct(

    )
    {
        //No session access from constructor work arround
        // $this->middleware(function ($request, $next)
        // {
        //     $this->user = session('data')->user;
        //     return $next($request);
        // });
    }

    public function index()
    {
        $data['breadcrumb'] = [
            'parent' => 'Dashboard',
            'child' => ''
        ];
        return view('backend.dashboard.index', $data);
    }
}

app/Http/Controllers/Backend/JournalController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Traits\FlashMessageTraits;
use DB;
class JournalController extends Controller
{
    use FlashMessageTraits;
    function __construct(

    )
    {
        //No session access from constructor work arround
        // $this->middleware(function ($request, $next)
        // {
        //     $this->user = session('data')->user;
        //     return $next($request);
        // });
    }

    public function index()
    {
        $data['breadcrumb'] = [
            'parent' => 'Category',
            'child' => 'List Category'
        ];
        $data['listcategory'] = $this->listcategory();
        return view('backend.journal.index', $data);
    }

    public function detail($id)
    {
        $data['id'] = $id;
        $data['detail'] = $this->detaildata($id);
        return view('backend.journal.detail', $data);
    }

    public function create(Request $request)
    {

        $sessionUser = $request->session()->get('session_user');
        $input = $request->all();
		$data = DB::table('journals')->insert(
			['created_by' => $sessionUser->id, 'title' => $input['title'], 'body' => $input['body'], 'status' => $input['status'], 'created_at' => date('Y-m-d H:i:s')]
		);
		if ( $data ) {
			$result = array( 'success' => true, 'message' => 'Journals Created Success!');
			return response()->json($result);
		} else {
			$result = array( 'success' => false, 'message' => 'Journals Created Failed!' );
			return response()->json($result);
		}
    }


	public function listcategory(){
		$hasil = DB::select('SELECT *
								FROM journals');
		return $hasil;
	}

	public function detaildata($id){
        $hasil = DB::table('journals')
        ->where('id',  $id)->first();
		return $hasil;
	}


}

resources/views/backend/uom/index.blade.php
@extends('backend.layouts.backend')

@section('content')

    <!--begin::Toolbar-->
    <div id="kt_app_toolbar" class="app-toolbar py-6">
        <!--begin::Toolbar container-->
        <div id="kt_app_toolbar_container" class="app-container container-xxl d-flex align-items-start">
            <!--begin::Toolbar container-->
            <div class="d-flex flex-column flex-row-fluid">
                <!--begin::Toolbar wrapper-->
                <div class="d-flex align-items-center pt-1">
                    <!--begin::Breadcrumb-->
                    <ul class="breadcrumb breadcrumb-separatorless fw-semibold">
                        <!--begin::Item-->
                        <li class="breadcrumb-item text-white fw-bold lh-1">
                            <a href="../../demo34/dist/index.html" class="text-white text-hover-primary">
                                <i class="ki-outline ki-home text-gray-700 fs-6"></i>
                            </a>
                        </li>
                        <!--end::Item-->
                        <!--begin::Item-->
                        <li class="breadcrumb-item">
                            <i class="ki-outline ki-right fs-7 text-gray-700 mx-n1"></i>
                        </li>
                        <!--end::Item-->
                        <!--begin::Item-->
                        <li class="breadcrumb-item text-white fw-bold lh-1">Master Data</li>
                        <!--end::Item-->
                        <!--begin::Item-->
                        <li class="breadcrumb-item">
                            <i class="ki-outline ki-right fs-7 text-gray-700 mx-n1"></i>
                        </li>
                        <!--end::Item-->
                        <!--begin::Item-->
                        <li class="breadcrumb-item text-white fw-bold lh-1">Unit Of Measures</li>
                        <!--end::Item-->
                    </ul>
                    <!--end::Breadcrumb-->
                </div>
                <!--end::Toolbar wrapper=-->
                <!--begin::Toolbar wrapper=-->
                <div class="d-flex flex-stack flex-wrap flex-lg-nowrap gap-4 gap-lg-10 pt-13 pb-6">
                    <!--begin::Page title-->
                    <div class="page-title me-5">
                        <!--begin::Title-->
                        <h1 class="page-heading d-flex text-white fw-bold fs-2 flex-column justify-content-center my-0">Unit Of Measures
                        <!--begin::Description-->
                        <span class="page-desc text-gray-700 fw-semibold fs-6 pt-3">List Unit Of Measures</span>
                        <!--end::Description--></h1>
                        <!--end::Title-->
                    </div>
                    <!--end::Page title-->
                </div>
                <!--end::Toolbar wrapper=-->
            </div>
            <!--end::Toolbar container=-->
        </div>
        <!--end::Toolbar container-->
    </div>
    <!--end::Toolbar-->
    <!--begin::Wrapper container-->
    <div class="app-container container-xxl">
        <!--begin::Main-->
        <div class="app-main flex-column flex-row-fluid" id="kt_app_main">
            <!--begin::Content wrapper-->
            <div class="d-flex flex-column flex-column-fluid">
                <!--begin::Content-->
                <div id="kt_app_content" class="app-content flex-column-fluid">
                    <!--begin::Products-->
                    <div class="card card-flush" style="height: 70vh;">
                        <!--begin::Card header-->
                        <div class="card-header align-items-center py-5 gap-2 gap-md-5">
                            <!--begin::Card title-->
                            <div class="card-title">
                                <!--begin::Search-->
                                <div class="d-flex align-items-center position-relative my-1">
                                    <i class="ki-outline ki-magnifier fs-3 position-absolute ms-4"></i>
                                    <input type="text" data-kt-ecommerce-product-filter="search" class="form-control form-control-solid w-250px ps-12" placeholder="Search Product" />
                                </div>
                                <!--end::Search-->
                            </div>
                            <!--end::Card title-->
                            <!--begin::Card toolbar-->
                            <div class="card-toolbar flex-row-fluid justify-content-end gap-5">
                                <!--begin::Add product-->
                                <a href="#" data-bs-toggle="modal" data-bs-target="#modal_add_category" class="btn btn-primary">Add Unit Of Measures</a>
                                <!--end::Add product-->
                            </div>
                            <!--end::Card toolbar-->
                        </div>
                        <!--end::Card header-->
                        <!--begin::Card body-->
                        <div class="card-body pt-0">
                            <!--begin::Table-->
                            <table class="table align-middle table-row-dashed fs-6 gy-5" id="kt_ecommerce_products_table">
                                <thead>
                                    <tr class="text-start text-gray-400 fw-bold fs-7 text-uppercase gs-0">
                                        <th class="">ID</th>
                                        <th class="min-w-200px">Name</th>
                                        <th >Description</th>
                                        <th class="text-end min-w-70px">Actions</th>
                                    </tr>
                                </thead>
                                <tbody class="fw-semibold text-gray-600">
                                    @php($sl=1)
                                        @foreach($listcategory as $category)
                                            <tr>
                                                <td>{{$sl}}</td>
                                                <td>{{$category->name}}</td>
                                                <td>{{$category->description}}</td>
                                                <td class="text-end">
                                                    <a href="#" class="btn btn-sm btn-light btn-flex btn-center btn-active-light-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">Actions
                                                    <i class="ki-outline ki-down fs-5 ms-1"></i></a>
                                                    <!--begin::Menu-->
                                                    <div class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 w-125px py-4" data-kt-menu="true">
                                                        <!--begin::Menu item-->
                                                        <div class="menu-item px-3">
                                                            <a href="#" class="menu-link px-3">Detail</a>
                                                        </div>
                                                        <div class="menu-item px-3">
                                                            <a href="#" class="menu-link px-3">Edit</a>
                                                        </div>
                                                        <!--end::Menu item-->
                                                        <!--begin::Menu item-->
                                                        <div class="menu-item px-3">
                                                            <a href="#" class="menu-link px-3" data-kt-ecommerce-product-filter="delete_row">Delete</a>
                                                        </div>
                                                        <!--end::Menu item-->
                                                    </div>
                                                    <!--end::Menu-->
                                                </td>
                                            </tr>

                                        @php($sl++)
                                    @endforeach
                                </tbody>
                            </table>
                            <!--end::Table-->
                        </div>
                        <!--end::Card body-->
                    </div>
                    <!--end::Products-->
                </div>
                <!--end::Content-->
            </div>
            <!--end::Content wrapper-->
        </div>
        <!--end:::Main-->
		<!--begin::Modal - Create Campaign-->
		<div class="modal fade" id="modal_add_category" tabindex="-1" aria-hidden="true">
			<!--begin::Modal dialog-->
			<div class="modal-dialog modal-lg p-9">
				<!--begin::Modal content-->
				<div class="modal-content modal-rounded">
					<!--begin::Modal header-->
					<div class="modal-header py-7 d-flex justify-content-between">
						<!--begin::Modal title-->
						<h2>Add Unit Of Measures</h2>
						<!--end::Modal title-->
						<!--begin::Close-->
						<div class="btn btn-sm btn-icon btn-active-color-primary" data-bs-dismiss="modal">
							<i class="ki-outline ki-cross fs-1"></i>
						</div>
						<!--end::Close-->
					</div>
					<!--begin::Modal header-->
					<!--begin::Modal body-->
					<div class="modal-body scroll-y m-5">

						<!--begin::Input group-->
								<div class="mb-10 fv-row">
									<!--begin::Label-->
									<label class="required form-label mb-3">Name</label>
									<!--end::Label-->
									<input type="text" class="form-control form-control-lg " id="category_name" name="category_name" placeholder="Name" value="" />
								</div>
								<div class="mb-10 fv-row">
									<!--begin::Label-->
									<label class="required form-label mb-3">Description</label>
									<!--end::Label-->
									<textarea class="form-control" id="description" name="description"  data-kt-autosize="true"></textarea>
								</div>

								<div class=" d-flex justify-content-end py-6">
									<button type="reset" class="btn btn-light  me-2" style="border: 1px solid #cfc7c7">Discard</button>

									<button type="button" onClick="createData()" class="btn btn-primary">Save</button>
								</div>

						</div>
					</div>
					<!--begin::Modal body-->
				</div>
			</div>
		</div>
@endsection

@section('onpage-js')
<script>
function createData(){

       var name   = $('#category_name').val();
       var description   = $('#description').val();
       var parent_id   = $('#parent_id').val();

              if(name){
                  var datapost={
                      "name"  :   name,
                      "description"  :   description,
                      "parent_id"  :   parent_id,
                    };
                    $.ajax({
                      type: "POST",
                      url: "{{route('heykama.addcategory')}}",
                      data : JSON.stringify(datapost),
                      headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                      dataType: 'json',
                      contentType: 'application/json; charset=utf-8',
                      success: function(response) {
                        if (response.success == true) {

                            swal({
                                  title: 'Success!',
                                  text: response.message,
                                  type: 'success',
                                  showCancelButton: false,
                                  confirmButtonText: 'Ok'
                              }).then(function () {
                                 window.location.href = "{{route('heykama.category')}}";
                              })



                        } else{
                          swal("Failed!", response.message, "error");
                        }
                      }
                    });
              }else{
                  swal("Failed!", "Nama Belum Terisi!", "error");
              }

  }

</script>

@endsection